# Generated by Django 2.2.13 on 2020-06-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="test",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="testt",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
