# Generated by Django 2.2.13 on 2020-06-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200630_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='fhsrths',
            field=models.ManyToManyField(blank=True, related_name='customtext_fhsrths', to='home.CustomText'),
        ),
    ]
