# Generated by Django 2.2.13 on 2020-06-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customtext_fhsrths'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='fhsrths',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='test',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='testt',
        ),
    ]
