# Generated by Django 2.2.13 on 2020-06-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200630_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='erfrefrf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sdfarqjhgjg',
        ),
    ]
